name: ModdingMinecraft
main: me.jamoowns.moddingminecraft.ModdingMinecraft
version: 0.0.2
api-version: 1.16
commands:
    mm:
        description: MinecraftModders related commands
        usage: /mm <activate/deactivate> FEATURE