package me.jamoowns.moddingminecraft.features;

public enum Feature {
	BATTLE_ROYALE, RANDOM_CHESTS, ZOMBIE_BELL, RANDOM_ENCHANT, EGG_WITCH, RANDOM_BUCKET, PLAYER_TRAIL, IRON_GOLEM,
	FUNKY_MOB_DEATH, WINFRED, STABLE_WEATHER
}
